import re
import os

if __name__ == "__main__":
    info = open("Desktop/InfoUitMail.txt", "r").read()
    
    voornaam = re.findall("Voornaam: (.+)", info)
    voorletters = re.findall("Voorletters: (.+)", info)
    tussenvoegsels = re.findall("Tussenvoegsel:(.*)", info)
    Achternaam = re.findall("Achternaam: (.+)", info)
    WURaccount = re.findall("WUR\-account \(indien mogelijk\) Bijv\. bond007: (.+)", info)
    Email = re.findall("E-mail \(bij voorkeur WUR-mail\): (.+)", info)
    Email2 = re.findall("Alternatieve E-mail \(geen WUR-mail\): (.+)", info)
    Telefoonnummer = re.findall("Telefoonnummer \(als: 06-12345678\): (.+)", info)
    geboortedatum = re.findall("Geboortedatum: (.+)\(", info)
    adres = re.findall("Adres \(Straat \+ Huisnummer\): (.+)", info)
    postcode = re.findall("Postcode: (.+)", info)
    plaats = re.findall("Woonplaats: (.+)", info)
    ML = re.findall("Ik wil graag de Missing Link \(verenigingsblad\) ontvangen: (.+)", info)
    startjaar = re.findall("Startjaar Studie: (.+)", info)
    bachelor = re.findall("Ik ben: (.+)", info)
    opmerkingen = re.findall("Eventuele opmerkingen: (.+)", info)
    iban = re.findall("IBAN: (.+)", info)
    datum = re.findall("Datum: (.+) \(", info)
    tekenplaats = re.findall("Plaats: (.+)", info)

    #schrijf csv bestand
    openfile = open("Desktop/heringeschreven.csv", "w")

    openfile.write("WUR account;Naam;Emailadres;Voorletters;Tussenvoegsel;Achternaam;Geboortedatum;Rekeningnummer;Telefoon;Postcode;Woonplaats;Emailadres extra/ouders;Missing Link;startjaar;Adres + Nr.;Voornaam+tussenvoegsels;NR. MACHTIGING;Wur-email ledensysteem\n")
    
    for i in range(len(voornaam)):
        openfile.write(WURaccount[i].strip())
        openfile.write(";")
        openfile.write(voornaam[i].strip())
        openfile.write(";")
        openfile.write(Email[i].strip())
        openfile.write(";")
        openfile.write(voorletters[i].strip())
        openfile.write(";")
        openfile.write(tussenvoegsels[i].replace(":", "").strip())
        openfile.write(";")
        openfile.write(Achternaam[i].strip())
        openfile.write(";")
        openfile.write(geboortedatum[i].strip())
        openfile.write(";")
        openfile.write(iban[i].strip())
        openfile.write(";")
        openfile.write(Telefoonnummer[i].strip())
        openfile.write(";")
        openfile.write(postcode[i].strip())
        openfile.write(";")
        openfile.write(plaats[i].strip())
        openfile.write(";")
        openfile.write(Email2[i].strip())
        openfile.write(";")
        openfile.write(ML[i].strip())
        openfile.write(";")
        openfile.write(startjaar[i].strip())
        openfile.write(";")
        openfile.write(adres[i].strip())
        openfile.write(";;;")
        openfile.write(Email[i].strip())
        openfile.write("\n")
    openfile.close()
